# -*- coding: utf-8 -*-
"""ER-NER baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LeyP7g5autEHKYQ3H8rQCaIdOJkdMCPN
"""

import json
import os
dataset_folder="dataset/"


dataset=list()
with open(os.path.join(dataset_folder,"train.json"), "r", newline="") as f:
    train=json.load(f)

with open(os.path.join(dataset_folder,"val.json"), "r", newline="") as f:
    val=json.load(f)

with open(os.path.join(dataset_folder,"test-real.json"), "r", newline="") as f:
    test=json.load(f)

dataset.extend(train)
dataset.extend(val)
dataset.extend(test)
print(len(dataset))
print(len(train))
print(len(val))
print(len(test))

#Convert Polarity Label

def convertPolarity(dataset):
  new_dataset=list()

  for entry in dataset:
    new_entry=dict()
    new_entry["doc_id"]=entry["doc_id"]
    new_entry["text"]=entry["text"]
    new_entry["annotations"]=list()

    for annotation in entry["annotations"]:
      new_annotation=annotation.copy()
      if annotation["label"]=="Alergias medicamentosas":
        if annotation["Polaridade"]=="Positiva":
            new_annotation["label"]="Alergias medicamentosas positiva"
        else:
            new_annotation["label"]="Alergias medicamentosas negativa"
      else:
        new_annotation["label"]=annotation["label"]
      new_entry["annotations"].append(new_annotation)
    new_dataset.append(new_entry)
  return new_dataset

train=convertPolarity(train)
val=convertPolarity(val)
test=convertPolarity(test)

train[2:7]



import pandas as pd
import os
import pickle
similarity_map_df=pd.read_csv(os.path.join(dataset_folder,"similarity_map.csv"))

train[0]


def getTextSpanFromPosition(entry):
  text=entry["text"]
  annotations_res=list()
  for annotation in entry["annotations"]:
    temp=dict()
    temp["begin"]=annotation["begin"]
    temp["end"]=annotation["end"]
    temp["span"]=text[temp["begin"]:temp["end"]]
    temp["label"]=annotation["label"]
    annotations_res.append(temp)
  return annotations_res

import langextract as lx
def getExamples(doc_id,train_dataset):
  """
  Givena  doc_id from the training get the annotation from the training dataset
  """
  #print(doc_id)
  entry=[x for x in train_dataset if x["doc_id"]==doc_id][0]
  #print(extractions)
  annotations=getTextSpanFromPosition(entry)

  #print(extractions)
  lx_extract=list()
  for annotation in annotations:
    lx_extract.append(lx.data.Extraction(extraction_class=annotation["label"], extraction_text=annotation["span"]))


  #print(narrative,lang)
  # Define example data with entities in order of appearance
  examples = [
      lx.data.ExampleData(
          text=entry["text"],
          extractions=lx_extract
      )
  ]
  return examples

id_ex=train[0]["doc_id"]
getTextSpanFromPosition(train[0])
getExamples(id_ex,train)

def getDynamicExample(doc_id,train,similarity_map_df):
  matching=similarity_map_df[similarity_map_df["doc_id"]==doc_id].iloc[0]
  most_similar_id=matching["train_most_similar_id"]
  examples=getExamples(most_similar_id,train)
  return examples

getDynamicExample(test[0]["doc_id"],train,similarity_map_df)



prompt='''
Extrai entidades clínicas estruturadas de notas de admissão no serviço de urgência, em português europeu.

Extrai apenas informação explicitamente presente no texto. Não infiras, normalizes nem acrescentes entidades.

Classes de entidades:

1. principal_diagnosis
- Diagnóstico principal, clinicamente específico, associado ao episódio atual.
- Extrai o diagnóstico completo tal como escrito.
- Se houver vários diagnósticos principais listados, extrai apenas o primeiro.
- Não extraias sintomas, antecedentes, procedimentos ou categorias vagas, salvo se forem claramente o diagnóstico principal.

2. usual_medication
- Medicação habitual, crónica ou domiciliária do doente.
- Extrai cada medicamento separadamente.
- Inclui nome, dose, forma, via, frequência, horário e instruções, quando presentes.
- Não extraias medicação prescrita apenas para o episódio atual, salvo se for indicada como habitual/crónica.

3. drug_allergy
- Alergias medicamentosas e ausência explícita de alergias medicamentosas.
- Em alergias positivas, extrai o medicamento ou classe farmacológica.
- Em alergias negativas, extrai apenas a expressão de ausência, sem o marcador de negação, por exemplo sem “sem”.
- Atribui polaridade:
  - positive: alergia medicamentosa presente
  - negative: ausência explícita de alergias medicamentosas

Regras gerais:
- Mantém ortografia, abreviaturas e acentos originais.
- Extrai spans mínimos mas completos.
- Não juntes medicamentos ou alergias separadas.
- Não devolvas entidades ausentes.
- Não extraias alergias não medicamentosas.
- Não extraias antecedentes pessoais, salvo se forem claramente o diagnóstico principal do episódio atual.
'''

def extract_info_iaedu(prompt,example_annotations,input_text,model):

  # Define extraction prompt
  result = lx.extract(
    text_or_documents=input_text,
    prompt_description=prompt,
    examples=example_annotations,
    model=model
)
  return result

"""#AMALIA with IAEDU"""

import requests
import json

import re

def clean_output(text: str) -> str:
    # Extract all fenced blocks
    blocks = re.findall(r"```(?:json)?\s*(.*?)```", text, re.DOTALL)

    if blocks:
        return blocks[0].strip()

    # If no fenced blocks, try to extract raw JSON
    json_match = re.search(r"\{.*\}", text, re.DOTALL)
    if json_match:
        return json_match.group(0).strip()

    return text.strip()




from langextract.providers.openai import OpenAILanguageModel
amalia_model= OpenAILanguageModel(
                model_id=model_id,
                api_key="not-needed",
                base_url=base_url + "/v1",
                temperature=0,
                frequency_penalty=0,
                presence_penalty=0
)

import langextract as lx

def extract_info_iaedu(prompt,example_annotations,input_text,model):

  # Define extraction prompt
  result = lx.extract(
    text_or_documents=input_text,
    prompt_description=prompt,
    examples=example_annotations,
    model=model
)
  return result


model =amalia_model
#input_text=test[0]["text"]
#annotations_examples=getDynamicExample(test[0]["doc_id"],train,similarity_map_df)
#res=extract_info_iaedu(prompt=prompt,example_annotations=annotations_examples,input_text=input_text,model=model)


output_folder="results/amalia"


import tqdm
import os

output_folder="results"
experiment_folder=os.path.join(output_folder,"extraction","amalia")
if(not experiment_folder):
    os.makedirs(os.path.join(output_folder,"amalia"))
    print("folder created")
for entry in test:
    #if document in results
    if(os.path.exists(os.path.join(experiment_folder,str(entry["doc_id"])+".json"))):
      print("already processed",entry["doc_id"])
      continue
    examples= getDynamicExample(entry["doc_id"],train=train, similarity_map_df=similarity_map_df)
    input_text=entry["text"]
    res=extract_info_iaedu(input_text=input_text,example_annotations=examples,prompt=prompt,model=model)

    print("processed!!!",entry["doc_id"])

    lx.io.save_annotated_documents([res], output_name=str(entry["doc_id"])+".json", output_dir=experiment_folder)
    html_content = lx.visualize(os.path.join(experiment_folder,str(entry["doc_id"])+".json"))

    with open(os.path.join(experiment_folder,str(entry["doc_id"])+".html"), "w") as f:
        if hasattr(html_content, 'data'):
            f.write(html_content.data)  # For Jupyter/Colab
        else:
            f.write(html_content)

    print("written!!!",entry["doc_id"])



